services:
  checkboxes-postgres-db:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgre
  auth-server-oidc-valkey:
    image: valkey/valkey
    container_name: auth-server-oidc-valkey
    ports:
      - '6379:6379'